targetInstance: ${TEST_URL:http://localhost:8090}
s2s-url: ${S2S_URL_FOR_TESTS:http://127.0.0.1:8502}
s2s-name: rd_professional_api
# Test key - not used in any deployed vaults or services
s2s-secret: ${S2S_SECRET:SZDUA3L7N32PE2IS}
spring:
  flyway:
    enabled: false
## Secure roles configuration
exui.role:
  hmcts-admin: SuperUser
  pui-user-manager: pui-user-manager
  pui-organisation-manager: pui-organisation-manager
  pui-finance-manager: pui-finance-manager
  pui-case-manager: pui-case-manager