targetInstance: ${TEST_URL:http://rd-professional-api-demo.service.core-compute-demo.internal}
s2s-url: ${S2S_URL_FOR_TESTS:http://rpe-service-auth-provider-demo.service.core-compute-demo.internal}
s2s-name: rd_professional_api

idam.api.url: ${IDAM_URL:https://idam-api.demo.platform.hmcts.net}
generated.user.email.pattern: ${GENERATED_USER_EMAIL_PATTERN:freg-test-user-%s@feemail.com}
test.url: ${TEST_URL:http://rd-professional-api-demo.service.core-compute-demo.internal}
test.user.password: ${TEST_USER_PASSWORD:Hmcts123}
#oauth2.redirect.uri: ${OAUTH2_REDIRECT_URI:https://rd-professional-api-preview.service.core-compute-preview.internal/oauth2redirect}
oauth2.client.id: ${OAUTH2_CLIENT_ID:rd-professional-api}
oauth2.client.secret: ${OAUTH2_CLIENT_SECRET:cc5f2a6-9690-11e9-bc42-526af7764f64}

idam.auth.tokenAuth: ${IDAM_TOKEN_ATUH:cmQtcHJvZmVzc2lvbmFsLWFwaTpjYzVmMmE2LTk2OTAtMTFlOS1iYzQyLTUyNmFmNzc2NGY2NA==}
idam.auth.redirectUrl: ${OAUTH2_REDIRECT_URI:https://rd-professional-api-demo.service.core-compute-demo.internal/oauth2redirect}
s2s-secret: ${S2S_SECRET:4QKOKOOTZN7KOHYG}
spring.flyway.enabled: false
## Secure roles configuration 1
exui.role.hmcts-admin: prd-admin
exui.role.pui-user-manager: pui-user-manager
exui.role.pui-organisation-manager: pui-organisation-manager
exui.role.pui-finance-manager: pui-finance-manager
exui.role.pui-case-manager: pui-case-manager


