apiVersion: v2
appVersion: "1.0"
description: A Helm chart for rd-professional-api
name: rd-professional-api
home: https://github.com/hmcts/rd-professional-api
version: 0.0.28
maintainers:
  - name: Reference Data Team
dependencies:
  - name: java
    version: 5.0.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
