java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    POSTGRES_NAME: "{{ .Values.postgresql.postgresqlDatabase}}"
    POSTGRES_USERNAME: "{{ .Values.postgresql.postgresqlUsername}}"
    POSTGRES_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
    LAUNCH_DARKLY_ENV: "preview"
  postgresql:
    enabled: true
    postgresqlUsername: dbrefdata
    postgresqlPassword: dbrefdata
    postgresqlDatabase: dbrefdata
  keyVaults:
    rd:
      secrets:
        - LD-SDK-KEY
        - AppInsightsInstrumentationKey
        - microservicekey-rd-professional-api