java:
  applicationPort: 8090
  environment:
    POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    POSTGRES_NAME: "{{ .Values.postgresql.postgresqlDatabase}}"
    POSTGRES_USER: "{{ .Values.postgresql.postgresqlUsername}}"
    POSTGRES_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
    POSTGRES_PORT: 5432
    LOGBACK_REQUIRE_ALERT_LEVEL: 'false'
    LOGBACK_REQUIRE_ERROR_CODE: 'false'
  image: 'https://hmcts.azurecr.io/hmcts/draft-store-service:latest'
  postgresql:
    postgresqlUsername: dbrefdata
    postgresqlPassword: dbrefdata
    postgresqlDatabase: dbrefdata
    service:
      port: 5432
  keyVaults:
    "s2s":
      resourceGroup: rpe-service-auth-provider
      secrets:
        - microservicekey-rd-professional-api
