java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    POSTGRES_NAME: "{{ .Values.postgresql.auth.database}}"
    POSTGRES_USERNAME: "{{ .Values.postgresql.auth.username}}"
    POSTGRES_PASSWORD: "{{ .Values.postgresql.auth.password}}"
    LAUNCH_DARKLY_ENV: "preview"
    CONTAINER_NAME: rd-prd-data
    SCHEDULER_ENABLED: false
    CRON_EXPRESSION: "* */10 * * * *"
  postgresql:
    enabled: true
    auth:
      username: dbrefdata
      password: dbrefdata
      database: dbrefdata
  keyVaults:
    rd:
      secrets:
        - name: LD-SDK-KEY
          alias: LD_SDK_KEY
        - name: app-insights-connection-string
          alias: app-insights-connection-string
        - name: professional-api-s2s-secret
          alias: PROFESSIONAL_API_S2S_SECRET
        - name: rd-prd-storage-account-name
          alias: ACCOUNT_NAME
        - name: rd-prd-storage-account-primary-key
          alias: ACCOUNT_KEY
        - name: CONTAINER-NAME
          alias: CONTAINER_NAME

blobstorage:
  resourceGroup: rd-aso-preview-rg
  teamName: "RD"
  location: uksouth
  setup:
    containers:
      - rd-prd-data
  enabled: true