java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    POSTGRES_NAME: "{{ .Values.postgresql.auth.database}}"
    POSTGRES_USERNAME: "{{ .Values.postgresql.auth.username}}"
    POSTGRES_PASSWORD: "{{ .Values.postgresql.auth.password}}"
    LAUNCH_DARKLY_ENV: "preview"
    CCD_URL: https://ccd-user-profile-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  postgresql:
    enabled: true
    auth:
      username: dbrefdata
      password: dbrefdata
      database: dbrefdata
  keyVaults:
    rd:
      secrets:
        - name: LD-SDK-KEY
          alias: LD_SDK_KEY
        - name: ApplicationInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
        - name: professional-api-s2s-secret
          alias: PROFESSIONAL_API_S2S_SECRET
