java:
  applicationPort: 8090
  ingressHost: rd-professional-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: rd
  environment:
    POSTGRES_HOST: rd-professional-api-postgres-db-v16-{{ .Values.global.environment }}.postgres.database.azure.com
    POSTGRES_USERNAME: pgadmin
    POSTGRES_PORT: 5432
    CONTAINER_NAME: rd-prd-data
    S2S_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    USER_PROFILE_URL: http://rd-user-profile-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    OIDC_ISSUER_URL: https://forgerock-am.service.core-compute-idam-{{ .Values.global.environment }}.internal:8443/openam/oauth2/hmcts
    OPEN_ID_API_BASE_URI: https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/o
    IDAM_URL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    CCD_URL: http://ccd-user-profile-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    AUTH_IDAM_CLIENT_BASEURL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    LAUNCH_DARKLY_ENV: "{{ .Values.global.environment }}"
    SCHEDULER_ENABLED: false
    CRON_EXPRESSION: "* */10 * * * *"
  spotInstances:
    enabled: true
  image: 'hmctspublic.azurecr.io/rd/professional-api:latest'
  keyVaults:
    rd:
      secrets:
        - name: professional-api-POSTGRES-PASS
          alias: spring.datasource.password
        - name: app-insights-connection-string
          alias: app-insights-connection-string
        - name: LD-SDK-KEY
          alias: LD_SDK_KEY
        - name: rd-prd-storage-account-name
          alias: ACCOUNT_NAME
        - name: rd-prd-storage-account-primary-key
          alias: ACCOUNT_KEY
        - name: professional-api-s2s-secret
          alias: PROFESSIONAL_API_S2S_SECRET
  autoscaling:
    enabled: true
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
